### ISSUE TITLE
Nanofilt Error

### ISSUE THREAD

**Issue by damioresegun** [wdecoster/nanofilt#13]
Hi Wouter, 

I used pip install --upgrade to install Nanofilt (it only worked when I used sudo) however it still installing in the python2.7 dist packages and it seems that this is leading to the error seen below:

zcat ../Pore_FastQs/allFastQ_adapterRemoved.fastq.gz | NanoFilt -l 2000 | gzip > highQuality-reads.fastq.gz
Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 9, in <module>
    load_entry_point('NanoFilt==1.8.0', 'console_scripts', 'NanoFilt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 29, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures

Help?

Thanks
Dami

**Comment by wdecoster** [comment]
Yes, since I'm using a module specific to Python3 NanoFilt is no longer compatible with Python 2.7.

Is upgrading to Python 3 a problem, or could you make a separate environment?

**Comment by wdecoster** [comment]
I could try to make it compatible again, but I can't promise anything.

**Comment by wdecoster** [comment]
For installing without sudo you could add --user to pip install

**Comment by wdecoster** [comment]
Having thought about this, no, I will not keep my scripts compatible with Python2.7. Can you install this in a Python3 environment?

**Comment by damioresegun** [comment]
I have installed it in  Python3 environment and have been trying to fix it all day. No luck so far. Here is the error it is showing me. 
(nanofiltr) dro@scan-pc:~/Documents/NanoFilt_Try/environments/nanofiltr$ NanoFilt -h
Traceback (most recent call last):
  File "/home/dro/Documents/NanoFilt_Try/environments/nanofiltr/bin/NanoFilt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/dro/Documents/NanoFilt_Try/environments/nanofiltr/lib/python3.4/site-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/home/dro/Documents/NanoFilt_Try/environments/nanofiltr/lib/python3.4/site-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/home/dro/Documents/NanoFilt_Try/environments/nanofiltr/lib/python3.4/site-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/dro/Documents/NanoFilt_Try/environments/nanofiltr/lib/python3.4/site-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: nanoget>=0.15.0


At the end of the installation, it also showed this error in red:
Command /home/dro/Documents/NanoFilt_Try/environments/nanofiltr/bin/python3 -c "import setuptools, tokenize;__file__='/home/dro/Documents/NanoFilt_Try/environments/nanofiltr/build/biopython/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-x3tpro59-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/dro/Documents/NanoFilt_Try/environments/nanofiltr/include/site/python3.4 failed with error code 1 in /home/dro/Documents/NanoFilt_Try/environments/nanofiltr/build/biopython
Storing debug log for failure in /home/dro/.pip/pip.log


Thanks
Dami

**Comment by wdecoster** [comment]
What is your pip version? Have you tried updating pip?

**Comment by damioresegun** [comment]
Just updated pip to 9.0.1. Attempting to re-install NanoFilt now. Going through all the dependencies

**Comment by wdecoster** [comment]
There is no need to manually go through the dependencies. It should just work.

**Comment by damioresegun** [comment]
pip updated in the environment but not root. Nanofilt seems to still be installing in python2.7 dist packages even though in python3 environment

**Comment by wdecoster** [comment]
Try `python3 -m pip install NanoFilt`. Or `pip3 install NanoFilt`.

**Comment by damioresegun** [comment]
Finally installed!! Had to update pip3 as well to make it work. However, running is now producing a weird binary file. Though this may be my data itself. Will investigate and keep you updated. 

Thanks

Dami

**Comment by wdecoster** [comment]
How did you execute NanoFilt?

**Comment by damioresegun** [comment]
gunzip ../Pore_FastQs/allFastQ_adapterRemoved.fastq.gz | NanoFilt -l 2000 | gzip > highQuality_reads.fastq.gz

**Comment by wdecoster** [comment]
Did you use `gunzip -c` or just `gunzip`?

**Comment by damioresegun** [comment]
Just gunzip. I just tried it with -c and its working. Forgot about the -c label for gunzip. Whoops.

**Comment by wdecoster** [comment]
Glad the problem wasn't too hard to figure out. 

I'm closing this now, if you encounter further issues or have suggestions/feature requests I would be happy to hear them.

Cheers,
Wouter
