### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by damioresegun** [wdecoster/nanofilt#15]
Hi, Just a quick question, is it possible to filter out reads that are greater than a certain length? i.e. a maximum length filter. 

Thanks
Dami

**Comment by wdecoster** [comment]
That's currently not possible, but can in theory be added. For which application would that be useful?

**Comment by damioresegun** [comment]
I'm currently using NanoFilt 2.0.0

**Comment by wdecoster** [comment]
Yes, but why would you want to filter for short reads?

**Comment by damioresegun** [comment]
Oh, I have a ridiculously long read that is skewing my data and would like to remove it.

**Comment by wdecoster** [comment]
Alright, if it's just for a single experiment then I think it is better to write a separate script for this rather than adding another option. I'll probably write a script later today.

**Comment by wdecoster** [comment]
[Here](https://gist.github.com/wdecoster/992a45e5012db6c66eef3455910e9132) you can find a script for performing maximum length filtering. Save it as e.g. `TooLong.py`
The usage is similar as NanoFilt:

`zcat yourfile.fastq.gz | python TooLong.py -l 100000 > shortreads.fastq`

Does that solve it?

**Comment by damioresegun** [comment]
Alright, that's great. Its possible that I may need it for more than one experiment however, a separate script should still work either way

Thanks alot

Dami

**Comment by wdecoster** [comment]
Late update: I've added a --maxlength flag in NanoFilt v2.1.1
