### ISSUE TITLE
Using a non-zipped file

### ISSUE THREAD

**Issue by bluessherpa** [wdecoster/nanofilt#16]
Is there a way to get NanoFilt to work without using a zipped file?

Thanks.
Novis John

**Comment by wdecoster** [comment]
Hi,

Certainly. Instead of using `gunzip/zcat` you can simply use `cat` to stream the file.
Is that what you are looking for?

Cheers,
Wouter

**Comment by bluessherpa** [comment]
I guess it is how it would be written in the command line

***********************************************
John P. Fellers, Ph.D.
Research Molecular Biologist

USDA-ARS-HWWGRU
Dept. of Plant Pathology
4008 Throckmorton Hall
Manhattan, KS  66506
785.532.2367
fax 785.532.6167
***********************************************

On Feb 5, 2018, at 10:29 AM, Wouter De Coster <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Certainly. Instead of using gunzip/zcat you can simply use cat to stream the file.
Is that what you are looking for?

Cheers,
Wouter

**Comment by wdecoster** [comment]
`cat myfile.fastq | NanoFilt -q 10 > myfilteredfile.fastq`

**Comment by bluessherpa** [comment]
Thank you very much!!!!!  It worked great!!!

**Comment by wdecoster** [comment]
Please let me know if that doesn't work, or if you have other issues, suggestions or feature requests.
