### ISSUE TITLE
No module named 'nanofilt'

### ISSUE THREAD

**Issue by jwsbio** [wdecoster/nanofilt#19]
Dear all:
I had sucessfully installed Anaconda3 and NanoFilt on UBUNTU. However, no module of nanofilt or the command could be found even though I had created an evironment. Any suggestion?

Thank you very much.

**Comment by wdecoster** [comment]
Hi jwsbio,

Can you elaborate on how you installed the tools and how you are using them, and show me the exact error message(s) you get?

Cheers,
Wouter

**Comment by liny601** [comment]
Hello Wouter,

I have issue running the command NanoFilt as well. Nanofilt was successfully installed in pip according to the output message.

Below is the traceback: 
`cat BC01.fastq | NanoFilt -l 1500 > trimmed.fastq`
Traceback (most recent call last):
  File "/home/nanopore/.local/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/home/nanopore/.local/lib/python2.7/site-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
  File "/home/nanopore/.local/lib/python2.7/site-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/home/nanopore/.local/lib/python2.7/site-packages/nanoget/nanoget.py", line 28, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures

Any input is much appreciated.

Linh

**Comment by wdecoster** [comment]
Hi Linh,

As specified in the README NanoFilt is written for Python3, while your error message suggests you installed it for Python2.7. Make sure to use the right pip on systems with multiple python versions.

To be sure, you could use:

`python3 -m pip install nanofilt`

Cheers,
Wouter
