### ISSUE TITLE
filtering by quality

### ISSUE THREAD

**Issue by damioresegun** [wdecoster/nanofilt#20]
I was wondering if it is possible to do a filtration by length AND by quality. For example: I want to remove reads that are <2000bp and <Q10 thus leaving reads that are <2000bp but with >Q10 quality as well as reads longer than 2000bp.

**Comment by wdecoster** [comment]
The best way to do this would be to use NanoFilt twice, for reads smaller and larger than 2000, and combine the results.

**Comment by damioresegun** [comment]
This approach worked. Thanks Wouter
