### ISSUE TITLE
problem with running the test.sh

### ISSUE THREAD

**Issue by LinXialab** [wdecoster/nanofilt#23]
Hi,

I got some problem with running the test.sh. The error information as followed:

git clone https://github.com/wdecoster/nanotest.git
Cloning into 'nanotest'...
remote: Enumerating objects: 68, done.
remote: Total 68 (delta 0), reused 0 (delta 0), pack-reused 68
Unpacking objects: 100% (68/68), done.
Checking connectivity... done.

NanoFilt -h
./test.sh: line 5: NanoFilt: command not found

Could you please tell me how to fix this problem?

**Comment by wdecoster** [comment]
The test is mainly intended for continuous integration testing (TravisCI), but of course, you can use it you feel like. Have you installed NanoFilt?

**Comment by wdecoster** [comment]
Closing due to lack of reply...
