### ISSUE TITLE
use -s the sequencing_summary file to filt

### ISSUE THREAD

**Issue by Riverzrw** [wdecoster/nanofilt#24]
Hi,
I want to use sequencing_summary.txt file to filter the length < 500bp, and then use nanoplot to visualize. The shell used to filter as this: NanoFilt -s sequencing_summary.txt -l 500. But I can't obtain filtered sequencing_summary.txt file. Can my idea be implemented using nanofilt? 

Best,
Ruiwen Zhang

**Comment by wdecoster** [comment]
I agree that this not perfectly clear in the documentation, but the sequencing_summary.txt is used to make filtering of a fastq faster, not to filter the summary file itself.

NanoPlot itself has a --maxlength and --minlength argument, which will hide reads beyond that cut off in plots showing the read length. I assume that should solve your issue.

**Comment by Riverzrw** [comment]
Thanks, this is helpful to me.
