### ISSUE TITLE
Option for min_QUALITY (logic)or min_LENGTH

### ISSUE THREAD

**Issue by ms-gx** [wdecoster/nanofilt#25]
It would be handy if the std. behaviour of QUALITY (logical)and LENGTH can be changed by a flag into QUALITY (logical)or LENGTH.

This would be helpful for scenarios where I only want to discard the short low quality reads, since the long low qual. reads still might be helpful for de novo assembly.

**Comment by wdecoster** [comment]
Thanks for your suggestion, I'll think about it.

**Comment by wdecoster** [comment]
I think for a more complicated way of filtering you could either have a look at FiltLong, or apply some logic filters on the sequencing-summary.txt, which you can then use to get the reads of interest. I could help you with the latter solution if this is still relevant. I won't implement your request, to keep NanoFilt simple.
