### ISSUE TITLE
NanoFilt Won't run after install

### ISSUE THREAD

**Issue by peflanag** [wdecoster/nanofilt#26]
Hi, I installed NanoFilt and I cant seem to get it to run? Any ideas? I'm running it on macOS 10.13.6

Cheers,

Peter

<img width="1260" alt="screen shot 2019-02-26 at 10 15 22" src="https://user-images.githubusercontent.com/32863969/53405359-95651300-39af-11e9-8ccf-d5c4b5b5a265.png">

**Comment by wdecoster** [comment]
See https://github.com/wdecoster/NanoPlot/issues/122
