### ISSUE TITLE
Installation errors (with Python3)

### ISSUE THREAD

**Issue by pengelgau** [wdecoster/nanofilt#27]
Hi,

I've been trying to install nanofilt through pip (I have Python3) and although there seem to be no installation errors, when I try to run it I get a Traceback error that I'm unsure how to fix:
`NanoFilt -h
Traceback (most recent call last):
  File "/Users/vannockerlab/anaconda3/bin/NanoFilt", line 6, in <module>
    from nanofilt.NanoFilt import main
  File "/Users/vannockerlab/anaconda3/lib/python3.7/site-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
ImportError: cannot import name 'process_summary' from 'nanoget' (/Users/vannockerlab/anaconda3/lib/python3.7/site-packages/nanoget/__init__.py)`

I checked my nanoget installation and it seems fine.

Thanks

**Comment by wdecoster** [comment]
Oh no, it seems I broke something earlier today. My bad. I naively made some changes in nanoget and forgot to update other packages depending on it. Sorry about that :-/

Please try the following to get the earlier version back: 
```
pip uninstall nanoget
pip install nanoget==1.7.7
```

I'm on holiday for a week. I might fix it tomorrow on the plane if my battery doesn't run out.

**Comment by pengelgau** [comment]
That did the trick. Thanks for the speedy reply. Enjoy your holiday.

**Comment by wdecoster** [comment]
Should be fixed in the next version of NanoFilt, which I'll put on pypi/pip in a couple of minutes.
