### ISSUE TITLE
Weird peak in histogram of read length

### ISSUE THREAD

**Issue by Kata-Pa** [wdecoster/nanofilt#28]
Hi!
I have a question which might not be related to NanoFilt. I have some Nanopore Minion long reads basecalled with Flappie. I tried Nanoplot on them to check the statistics and everything looked ok. Then I did NanoFilt, as follows:
cat PoreChopped2_Flappie.fastq | NanoFilt -q 7 > NanoFilt_PoreChopped2_flappie.fastq
and run a nanoplot again to check if I did removed the low quality reads.
Now the thing is that I have a pretty high peak in the histogram of read length.
Do you have an idea if this has something to do with the filtering I applied or is it an issue of my dataset?
![histogram](https://user-images.githubusercontent.com/48205379/54687796-b89d6100-4b1c-11e9-9ec3-0db353027e19.png)
![log_transformed](https://user-images.githubusercontent.com/48205379/54687801-bb985180-4b1c-11e9-8370-3532594303f7.png)

**Comment by wdecoster** [comment]
Hi, that looks like the DNA Cs (calibration strand) spiked in (optionally) during library prep. It's a part of the lambda genome. I wrote https://github.com/wdecoster/nanolyse to remove it so that's something you could try.

Cheers,
Wouter

**Comment by Kata-Pa** [comment]
Ah you re right, I remember reading about this before , I ll have a look to the tool, thank you!
