### ISSUE TITLE
Command example

### ISSUE THREAD

**Issue by francoiskroll** [wdecoster/nanofilt#29]
The examples with pipes are nice, but don't you think it'd be good to have a basic example of the command with input > output?

I am having a bit of trouble writing a simple command without piping...

**Example**

`NanoFilt --maxlength 2000 test.fastq > filter.fastq`

> NanoFilt: error: unrecognized arguments: test.fastq

**Comment by wdecoster** [comment]
Currently, NanoFilt doesn't have other input options than stdin, but it is, of course, possible to add that to the tool. Do you have use cases in which piping is not sufficient and you would need a command without piping?

**Comment by francoiskroll** [comment]
I see. Just wanted to filter that single fastq based on length without doing anything else, really! I suppose it is possible to `stdin` a file without doing anything to it? I just think it might be more readable for not heavy command line users like me to support a classic `command --parameters input > output` syntax, but up to you.

**Comment by wdecoster** [comment]
Yeah that would be possible, I'll take a look at it next week, probably.

**Comment by wdecoster** [comment]
It is now (NanoFilt v2.3.0, available on pip) possible to specify an uncompressed fastq file directly on the command line, per your example:

`NanoFilt --maxlength 2000 test.fastq > filter.fastq`

Note that you could already do the equivalent using:

`cat test.fastq | NanoFilt --maxlength 2000 > filter.fastq`

In general, I don't like uncompressed fastq files, but that's up to you of course :-)
