### ISSUE TITLE
File streaming

### ISSUE THREAD

**Issue by Adamtaranto** [wdecoster/nanofilt#3]
Minor issue, zcat doesn't have the intended behaviour on OSX without directing stdin with "<".

i.e.
`zcat reads.fastq.gz | NanoFilt -q 12 --headcrop 75 | gzip > trimmed-reads.fastq.gz`

to 
`zcat < reads.fastq.gz | NanoFilt -q 12 --headcrop 75 | gzip > trimmed-reads.fastq.gz`

gzip/unzip '-c' would be more robust:

`gunzip -c reads.fastq.gz | NanoFilt -q 12 --headcrop 75 | gzip -c > trimmed-reads.fastq.gz`

**Comment by wdecoster** [comment]
Thanks for bringing this to my attention! I have changed the documentation to use `gunzip -c`.

Cheers,  
Wouter
