### ISSUE TITLE
Question about length and quality filters

### ISSUE THREAD

**Issue by jessMaia** [wdecoster/nanofilt#31]
Thanks so much for creating and making your software public! 

I had a question on the length and quality filters. In your example 
> NanoFilt.py -q 10 -l 500

does the filtered data have 

> quality >=10 and length >=500 
or 
> quality >10 and length > 500?

From looking at the code, I  assume it's the former but just wanted to check. Thanks!

**Comment by wdecoster** [comment]
Good question, it seems. I kinda expected that it would be `>=`, but checking the code it seems I have been inconsistent:

- the quality has to be higher: `quality >10`
- the length has to be same or higher: `length >=500`

Hmm that's not intuitive. I'll have to change that to make both "higher or equal".

**Comment by jessMaia** [comment]
Thanks for the clarification. That's all I needed!

**Comment by wdecoster** [comment]
In NanoFilt 2.4.0 I have **removed** this inconsistency. The quality filtering is now also using `>=`.
