### ISSUE TITLE
The output file from nanofilt can't be used for other module

### ISSUE THREAD

**Issue by henganl2** [wdecoster/nanofilt#33]
Hi, 

Thanks for developing this nice tool, I really like it. 

But I face some problem and need some help.  

I used nanofilt to process my file
`NanoFilt -v --logfile BC15.porechop.log -l 1000 --maxlength 2000 > ../Results/porechop/BC15.qualtrim.clean.fastq`

But then, the output file can't be further process through either fastqc or FASTX-Toolkit `fastq_to_fasta`. 

Here is the error message I got: 
`input file has unknown file format (not FASTA or FASTQ), first character =N (78)`

Let me know if I need to send you one of my fastq file. 
Thanks!

**Comment by wdecoster** [comment]
There is `-v` in your command, which will give you the version, so you shouldn't have that when processing data

**Comment by henganl2** [comment]
Thanks for your help! The code is working perfectly now!
