### ISSUE TITLE
use git tags

### ISSUE THREAD

**Issue by fizwit** [wdecoster/nanofilt#35]
For the purposes of reproducible science could you please tag your releases. Github will create a "release" once you push a tag. 
would be super useful if the tag matched your Python version string
  __version__ = "2.5.0"

thanks for this consideration,

**Comment by wdecoster** [comment]
Thanks for your suggestion! I'll make a release now, and I'll try to remember that in the future.

In which sense does this have an added value for reproducibility if I already consistently update the Python version string and push changes to PyPI?

**Comment by fizwit** [comment]
Thanks for creating the tag and for using ```__version__``` in your code. Once you tag software the release will be immutable and can be referenced by the tag name.  In the future someone will always be able to find version 2.5.0 if they want to reproduce a result.  It's a good thing. I have installed your software using and EasyBuild Easyconfig; https://easybuild.readthedocs.io/en/latest/
https://github.com/easybuilders/easybuild-easyconfigs/pull/8500
