### ISSUE TITLE
error "records in fastq files sholud start with @ character"

### ISSUE THREAD

**Issue by AngLiRNA** [wdecoster/nanofilt#37]
Hi,

When I running the Nanofilt under windows command, it shows this error. Since I am not good at bioinformatics . I used the zip file to do analysis.

Thank you,
Ang

**Comment by AngLiRNA** [comment]
sorry  can't load the picture

C:\Users\Nikon>"C:\Program Files\WinRAR\Rar.exe" -c C:\data\WT\201909
25_2238_MN22787_FAK92275_bfd36207\fastq_pass.zip | NanoFilt -q 0 --headcrop 5 |
"C:\Program Files\WinRAR\Rar.exe" -a > C:\data\WT\20190925_2238_MN227
87_FAK92275_bfd36207\trimmed-reads.fastq.zip
Traceback (most recent call last):
  File "C:\Users\Nikon\AppData\Local\Programs\Python\Python37\Scripts\NanoFilt-s
cript.py", line 11, in <module>
    load_entry_point('NanoFilt==2.5.0', 'console_scripts', 'NanoFilt')()
  File "c:\users\nikon\appdata\local\programs\python\python37\lib\site-packages\
nanofilt\NanoFilt.py", line 68, in main
    filter_stream(args.input, args)
  File "c:\users\nikon\appdata\local\programs\python\python37\lib\site-packages\
nanofilt\NanoFilt.py", line 189, in filter_stream
    for rec in SeqIO.parse(fq, "fastq"):
  File "c:\users\nikon\appdata\local\programs\python\python37\lib\site-packages\
Bio\SeqIO\__init__.py", line 661, in parse
    for r in i:
  File "c:\users\nikon\appdata\local\programs\python\python37\lib\site-packages\
Bio\SeqIO\QualityIO.py", line 1027, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "c:\users\nikon\appdata\local\programs\python\python37\lib\site-packages\
Bio\SeqIO\QualityIO.py", line 902, in FastqGeneralIterator
    "Records in Fastq files should start with '@' character")
ValueError: Records in Fastq files should start with '@' character

**Comment by wdecoster** [comment]
Hi,

> Since I am not good at bioinformatics . 

Doing bioinformatics on windows is only going to make things more difficult. I don't plan to support using windows. What you could try is to use the [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install-win10).  

> ValueError: Records in Fastq files should start with '@' character

The error is raised by biopython, telling you that your fastq file doesn't look like how it should. That's not something I can fix for you.

Cheers,
Wouter

**Comment by AngLiRNA** [comment]
Thank you so much

**Comment by wdecoster** [comment]
So is this issue solved?
