### ISSUE TITLE
Multi-thread mode

### ISSUE THREAD

**Issue by ConstantinV** [wdecoster/nanofilt#38]
Hi!
It will be great if multi thread mode for filtering have been added.
Thank you

**Comment by wdecoster** [comment]
I agree, and I'm happy to take a look at your pull request to implement this.

**Comment by joanmarticarreras** [comment]
> I agree, and I'm happy to take a look at your pull request to implement this.

Hi! Did this feature become available with last year release?

JMC

**Comment by wdecoster** [comment]
Please have a look at my chopper repository for a faster implementation of this tool.
