### ISSUE TITLE
Trimming of long read sequencing data

### ISSUE THREAD

**Issue by mareikepol** [wdecoster/nanofilt#39]
Hello,
I want to identificate 3'-end cleavage sites from Nanopore Sequencing data. For this analysis I need the last 100 nucleotides of each sequence. Since the read length varies 500nt-50kb, it is not possible for me to use --tailcrop or --headcrop. Is it possible to integrate a trimming function to keep the last 100 nucleotides?

Thank you!

**Comment by wdecoster** [comment]
Hi,

Thanks for your question, I don't think I'll add additional features to NanoFilt (unless there is high demand for those) but I have uploaded a script which should do precisely what you are asking for: https://github.com/wdecoster/nanofilt/blob/master/scripts/get_read_ends.py

If you save that code as `get_read_ends.py` (for example) you can use it as:

`python get_read_ends.py  --bases_from_end 500 reads.fastq.gz | gzip > last_500_bp.fastq.gz`

If you installed NanoFilt then all dependencies should also be okay for this script. The `--bases_from_end` parameter is by default set to 100bp.

Let me know if there is anything else I can help you with,
Wouter

**Comment by mareikepol** [comment]
Thank you very much for your quick help. I'll try your script now!
Mareike

**Comment by mareikepol** [comment]
Your script works! Thanks a lot.
Mareike

**Comment by wdecoster** [comment]
Good to hear!

**Comment by mareikepol** [comment]
Dear Wouter,
we got error with one of our datasets (the other data worked nicely). This data is direct RNA-Seq data, basecalled by guppy. Using your script I got error:


```
Traceback (most recent call last):
  File "get_read_ends.py", line 23, in <module>
    main()
  File "get_read_ends.py", line 8, in main
    for record in SeqIO.parse(gzip.open(args.fastq, 'rt'), "fastq"):
  File "/home/mareike/.local/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 661, in parse
    for r in i:
  File "/home/mareike/.local/lib/python3.6/site-packages/Bio/SeqIO/QualityIO.py", line 1027, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/home/mareike/.local/lib/python3.6/site-packages/Bio/SeqIO/QualityIO.py", line 948, in FastqGeneralIterator
    % (title_line, seq_len, len(quality_string)))
ValueError: Lengths of sequence and quality values differs  for c50a6b17-26ad-4c0e-abb6-8421d9ffca9f runid=d8b8c9a55d071d6d1f60f81cd1066715fbe21a8e sampleid=shTHOC5 read=60893 ch=194 start_time=2019-08-16T02:25:45Z (609 and 153).
```

I do not know what it the exact problem. May be an issue with read quality?
Would you kindly have a look and give us some comments?
Thank you very much for your support!
Mareike

**Comment by wdecoster** [comment]
Hi Mareike,

The error is raised by Biopython, which I use to parse fastq files.

> ValueError: Lengths of sequence and quality values differs for c50a6b17-26ad-4c0e-abb6-8421d9ffca9f runid=d8b8c9a55d071d6d1f60f81cd1066715fbe21a8e sampleid=shTHOC5 read=60893 ch=194 start_time=2019-08-16T02:25:45Z

It tells you that the read with identifier `c50a6b17-26ad-4c0e-abb6-8421d9ffca9f` is corrupted as the read length is not the same as the length of the quality string. I would suggest taking a look at that record. I would bet it's the last one in the file and something happened in a previous step, possibly a command which crashed or was interrupted.

Try something like this:
`zgrep -A 7 "c50a6b17-26ad-4c0e-abb6-8421d9ffca9f" reads.fastq.gz`
This will show you the line matching that read identifier and the 7 lines following that line, to show you the full fastq record and the next record (if there is one).
Note that for an non-compressed fastq file you should change `zgrep` to just `grep`.

Cheers,
Wouter

**Comment by mareikepol** [comment]
Hi Wouter,
thank you very much for your quick reply. I'll try as you suggested.
Mareike
