### ISSUE TITLE
Null output when head and tail crop len equal

### ISSUE THREAD

**Issue by Adamtaranto** [wdecoster/nanofilt#4]
Output file contains only headers of fastq records that pass filter (no sequence) when head and tail crop lengths are equal.

I think the issue is with this line: 

` print(record[args.headcrop:args.tailcrop].format("fastq"), end="")`

If --headcrop and --tailcrop =50 then the record is sliced as ['all positions above 50':'to position 50'] which is an empty string.

I whipped up my own mini-version of nanofilt, "[Yanagiba](https://github.com/Adamtaranto/Yanagiba/blob/master/yanagiba.py)", to just filter reads using Albacore summary files. Ran into the same issue and fixed it by making the tailtrim value either None or negatively signed if set.

**Comment by wdecoster** [comment]
Hi Adam,

Thanks for reporting this. That was a quite naive mistake I made there.
I have fixed this in version 1.2.0

Good job on Yanagiba. I see you use a different approach there for filtering. Would be interesting to test which is the fastest. You are also free to contribute to NanoFilt, although I must admit Yanagiba is a nicer name, perhaps harder to remember.

Cheers,  
Wouter

**Comment by Adamtaranto** [comment]
Feel free to poach anything you like from Yanagiba, it's all open source :) I agree, NanoFIlt is much easier to remember.

I played around with ways to make the fastq processing faster - one record at a time is very slow.
I'm sure you could batch process records from the fastq using multiprocessing/pool and mapping the trim function onto the seqrecord objects.

**Comment by wdecoster** [comment]
I haven't bothered to make this faster because I think the process following the filtering/trimming (mapping or compression) is going to be slower than the trimming itself. If you are piping it doesn't matter.
