### ISSUE TITLE
NanoFilt.py TypeError msg

### ISSUE THREAD

**Issue by marisalim** [wdecoster/nanofilt#40]
Hi, 

I've been using NanoFilt without any issues, but today I'm getting the error message below:
```
File "/anaconda3/lib/python3.6/site-packages/nanofilt/NanoFilt.py", line 194, in filter_stream
    if quality_check(rec.letter_annotations["phred_quality"]) >= args.quality \
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```
Looks like NanoFilt is still filtering my reads despite the TypeError, but can't figure out why this error is popping up now!

I just upgraded to v2.5.0 from v2.2.0, but got the error for both versions. The only difference was that the error was for `>` instead of `>=`. I run NanoFilt on a Mac with this command:
```
cat {myfastq} | NanoFilt -q {myqs} -l {minlen} --maxlength {maxlen} --log {mylog} > {myoutputfastq}
```

Thanks!

**Comment by wdecoster** [comment]
Do you think it would be possible to share your fastq file so that I can replicate this?

**Comment by marisalim** [comment]
Sure - what's the best way to share the file?

I think there is a file format issue somewhere, as I've just found that I don't get the error for other fastq files.

**Comment by wdecoster** [comment]
That indeed suggests it is something about the file, and not the script. I don't mind taking a look at it, but I don't know how large it is. You can find my email address on my profile or share with a Dropbox, Google drive, one drive link or similar

**Comment by marisalim** [comment]
Ok, just shared via Dropbox. The files are not too large. Would appreciate any help!

**Comment by marisalim** [comment]
These were the NanoFilt commands I ran:
```
cat givesnanofilterror.fastq | NanoFilt -q 7 -l 321 --maxlength 521 --logfile ../testmb > ../testmb.fastq
Traceback (most recent call last):
  File "/anaconda3/bin/NanoFilt", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/nanofilt/NanoFilt.py", line 68, in main
    filter_stream(args.input, args)
  File "/anaconda3/lib/python3.6/site-packages/nanofilt/NanoFilt.py", line 194, in filter_stream
    if quality_check(rec.letter_annotations["phred_quality"]) >= args.quality \
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

Command for the file that had no error message:
```
cat nonanofilterror.fastq | NanoFilt -q 7 -l 321 --maxlength 521 --logfile ../testqcat > ../testqcat.fastq
```

**Comment by marisalim** [comment]
Hi,
I'm still troubleshooting, but I tested out a snippet of your python code. I get the TypeError because the check_quality(rec.letter_annotations['phred_quality'] values are 'None' in the for loop (starting line 189). 

However, if I run an individual 'phred_quality' list through your ave_qual() function, I get a float:
```
theannot = [13, 26, 30, 42, 34, 24, 10, 10, 13, 16, 13, 6, 6, 6, 5, 5, 7, 11, 12, 20, 15, 15, 16, 15, 11, 8, 5, 17, 23, 23, 37, 33, 32, 28, 27, 23, 15, 3, 6, 6, 14, 9, 20, 19, 19, 20, 21, 31, 23, 22, 22, 24, 13, 24, 26, 25, 24, 16, 21, 9, 7, 8, 22, 23, 26, 29, 35, 35, 30, 4, 4, 7, 4, 20, 7, 16, 25, 25, 29, 36, 24, 14, 13, 24, 32, 26, 28, 22, 11, 13, 11, 10, 25, 9, 24, 21, 20, 16, 10, 3, 2, 5, 4, 19, 20, 38, 29, 30, 27, 26, 19, 17, 23, 27, 21, 21, 9, 19, 8, 24, 20, 15, 12, 5, 10, 17, 10, 3, 3, 3, 3, 15, 26, 26, 14, 19, 17, 24, 9, 5, 4, 5, 13, 13, 12, 6, 5, 14, 8, 2, 2, 1, 1, 3, 5, 16, 22, 3, 3, 10, 3, 20, 19, 24, 22, 17, 15, 26, 32, 34, 35, 17, 28, 28, 29, 30, 30, 23, 9, 9, 9, 20, 24, 32, 17, 17, 12, 12, 19, 14, 17, 6, 7, 7, 3, 3, 5, 6, 2, 7, 19, 27, 23, 19, 27, 10, 10, 16, 24, 31, 10, 8, 9, 14, 15, 19, 28, 12, 16, 32, 33, 29, 14, 11, 6, 12, 28, 27, 20, 27, 35, 20, 26, 25, 10, 16, 14, 9, 12, 9, 5, 3, 18, 17, 14, 13, 11, 4, 17, 13, 17, 10, 5, 5, 6, 18, 6, 4, 9, 25, 36, 35, 36, 27, 23, 19, 35, 41, 31, 26, 10, 7, 10, 5, 5, 5, 8, 6, 8, 12, 10, 16, 19, 20, 17, 16, 14, 21, 22, 33, 34, 27, 9, 10, 8, 3, 7, 15, 13, 14, 18, 11, 21, 29, 36, 34, 37, 28, 32, 35, 40, 32, 22, 18, 12, 11, 16, 10, 3, 17, 15, 23, 24, 19, 7, 2, 27, 33, 34, 15, 11, 6, 7, 16, 20, 24, 20, 38, 34, 40, 31, 31, 38, 27, 22, 18, 18, 3, 3, 8, 10, 14, 17, 21, 23, 26, 24, 28, 16, 16, 4, 27, 18, 20, 29, 33, 28, 34, 23, 22, 30, 28, 27, 24, 21, 17, 12, 14, 19, 23, 24, 27, 14, 8, 8, 12, 4, 5, 20, 11, 6, 10, 9, 11, 17, 25, 5, 16, 17, 13, 18, 16, 7, 7, 8, 9, 9, 10, 6, 16, 20, 3, 14, 6, 6, 4, 6, 2, 4, 4, 4, 14, 2, 14, 20, 19, 20, 18, 16, 14, 22, 9, 7, 13, 10]

tab=errs_tab(128)
themq = -10 * log(sum([tab[q] for q in theannot]) / len(theannot), 10)
print(themq)
> 9.904357477011038
```
So, I'm not sure why there's a problem in the loop.

**Comment by wdecoster** [comment]
Thanks for investigating... It's a public holiday in Belgium today, but I'll take a look at what's going on as soon as I am in front of the computer, which is probably Monday.

**Comment by marisalim** [comment]
Aha! I figured out the problem. I'm testing different demultiplexers, hence one demultiplexed fastq worked while the other was giving me the error. For the file that was failing, it is because there are just a few reads that got trimmed down to nothing, so the length of the quality score list `len(quals)` is 0. Consequently, the `ave_qual()` function gives divide by zero errors since the denominator is 0. I suppose this is not necessarily a common problem - perhaps adding a length check before calculating the average quality score is the simplest solution.

**Comment by wdecoster** [comment]
Great that you could figure it out!

To be precise, ave_qual did not divide by 0, as it checks if the list is empty... and returns None if it is. So it is already doing the length check you are suggesting, but it's not the best idea to just return None. I'll look into fixing that. Probably it should just return 0.

**Comment by marisalim** [comment]
Ah, ok. I oversimplified your ave_qual() function while I was tinkering, so I was getting the divide by zero error message. But yes, something a little more specific will save future headaches. Thanks!

**Comment by wdecoster** [comment]
As of v2.6.0, the ave_qual function will return a 0 for an empty read, and also print out a warning to stderr. Thanks for reporting this and figuring out what's wrong!
