### ISSUE TITLE
Nanofilt on a batch of files

### ISSUE THREAD

**Issue by Alxdu** [wdecoster/nanofilt#43]
First off, thank you for the tools you have made available. They're all great.

I'd like some advice on batch running nanofilt on every .fastq file in a folder with output to a differentt folder (or the same folder if the output files can have a suffix appended, e.g., _filtered) . Ideally something compatible with running the bash command through a jupyter notebook.

I tried using find + nanofilt but I cound't get it right:
`$ find pathtofolder/*.fastq -type f -execdir NanoFilt --length 1300 --maxlength 1800 -q 10 ???????`

Any advice on running nanofilt in batch is very appreciated. I have average understanding of unix and python, so I welcome a breakdown of details. Thank you

EDIT: I found the `for` loop to work with somewhat limited options to rename the output files
`$ for filename in ./*.fastq; do NanoFilt --length 1300 --maxlength 1800 -q 10 ${filename} > filtered/${filename}; done;`

Your feedback is appreciated.

**Comment by wdecoster** [comment]
Hi,

A great tool for things like that is [gnu-parallel](https://www.gnu.org/software/parallel/). The manual is quite extensive and there are lots of options and possibilities to finetune what you would need.

For your example I would suggest the following to put the files in a separate folder:
`ls *.fastq | parallel -j 16 --bar 'NanoFilt --length 1300 --maxlength 1800 -q 10 {} > filtered/{}'`
where `{}` is a placeholder for items in `ls *.fastq`.

Or with the command below to change the output file name and add a suffix
`ls *.fastq | parallel -j 16 --bar 'NanoFilt --length 1300 --maxlength 1800 -q 10 {} > {.}_filtered.fastq'`
where I used `{.}`, which is the name of the input without the last file extension (so without .fastq in this case).

Please let me know if that isn't entirely clear.

Cheers,
Wouter

**Comment by Alxdu** [comment]
Thank you very much for the examples provided. That tools looks like an elegant solution for multiple steps in my pipeline. 
I appreciate the the good work you're doing. 
Cheers,
Alex
