### ISSUE TITLE
ID missing from summary file

### ISSUE THREAD

**Issue by Electrocyte** [wdecoster/nanofilt#45]
When using Nanofilt with --summary flag, I have an issue with a few run IDs not existing inside the summary file. Would it be possible to either:

- Skip/discard them from the analysis (and output)
- Recalculate the quality score for that particular input

**Comment by wdecoster** [comment]
Thanks for the suggestion! NanoFilt 2.7.0 (now available on PyPI and soon on bioconda) will now, when using a summary file with a missing read, calculate the quality based on the quality scores (as would happen without a summary file) and just continue. It should still raise a warning, but just a warning, that the identifier was missing.
