### ISSUE TITLE
Installing Nanofilt with Miniconda3

### ISSUE THREAD

**Issue by Stephkoo** [wdecoster/nanofilt#46]
Hello

I am new to programming but I followed the instructions and didn't manage to install the program. I used Miniconda3 and tried one at a time the following:
conda install -c bioconda nanofilt
conda install -c bioconda/label/cf201901 nanofilt
but got the same result:
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions

I also tried with both Python3.7 and 3.8.

Would you help me on this? 

Thank you.

Regards
Stephanie
![Picture 1](https://user-images.githubusercontent.com/72193657/94789466-86560a80-0407-11eb-9483-2ae1d77ac6b5.png)

**Comment by wdecoster** [comment]
I see you are installing on Windows, which I don't use so giving support might be harder, but let's try.

1) You don't need `conda install -c bioconda/label/cf201901 nanofilt`.

2) Could you try installing this in a new environment to avoid problems with other dependencies?

```
conda create -n nanofilt-env -c bioconda nanofilt
conda activate nanofilt-env
NanoFilt -h
```

Thanks,
Wouter

**Comment by Stephkoo** [comment]
Hi Wouter

Thank you for your reply. 

I tried, and it gave me this in return.
![Picture 2](https://user-images.githubusercontent.com/72193657/94879301-69b2e480-0492-11eb-9a0e-b23cf5753ae2.png)

What do I do?

Best Regards
Stephanie

**Comment by wdecoster** [comment]
Is this WSL or just normal windows command line?

**Comment by Stephkoo** [comment]
Hi Wouter

I used Anaconda prompt (Miniconda3). Will that work? I can try to install WSL.

Best Regards
Stephanie

**Comment by wdecoster** [comment]
Hi Stephanie,

You will definitely need WSL.

Wouter

**Comment by Stephkoo** [comment]
Hi Wouter

The issue seems to have been solved after running it on WSL.

Thanks!

Best Regards
Stephanie
