### ISSUE TITLE
suggestion : add a brief output report

### ISSUE THREAD

**Issue by mariabernard** [wdecoster/nanofilt#47]
Hello 

I just start to deal with minion reads, and I use nanofilt to exclude reads previously to downstream analysis.
I just have a suggestion, it would be nice to have a short summary (or report as summary option already exists), to know how many reads are filtered out on which criteria : 
- number of input reads/bases
- number of trimmed reads/bases 
- too short reads
- too long
- poor quality reads
- final remaining reads/bases

thanks for developing this tool anyway!

**Comment by wdecoster** [comment]
Hi,

It's a good idea, but I fear keeping track of reads being filtered out for one of these criteria separately would slow down NanoFilt even more. At the moment all of these criteria are checked simultaneously. 

Cheers,
Wouter

**Comment by mariabernard** [comment]
really ?! 
I look at your code, what take time is computing average quality and gc content, but testing int values will not add too much time, no?
anyway, your code your choice! ;-)
