### ISSUE TITLE
NanoFilt produces empty output when tailcrop = 0

### ISSUE THREAD

**Issue by mlosilla** [wdecoster/nanofilt#49]
Hi,

Thank you for this great tool!

I found a small bug: when tailcrop = 0, the output is empty (the problem doesn't affect headcrop=0).

Why would I set tailcrop = 0? I am using NanoFilt in a pipeline. For some reads there is nothing to trim on the tail end, and therefore tailcrop is set to 0.

I took a look at your code, I think that when you trim the sequence with:

`rec[args.headcrop:args.tailcrop].format("fastq") `

the result is that rec becomes empty, since this command asks to slice rec up until the zero element.

I was able to patch your code by inserting :
`if args.tailcrop == 0:`
`    args.tailcrop = None`

inside main(), after line 38 (with proper indentation, I couldn't figure that out on this window)

The patch seems to be working for me.

Thanks
Mau

**Comment by wdecoster** [comment]
Aha, a great catch, thanks! I've added the changes you recommended.

Cheers,
Wouter
