### ISSUE TITLE
Unable to run NanoFilt after installation using pip

### ISSUE THREAD

**Issue by ksanjeetsinha** [wdecoster/nanofilt#5]
After I have installed using pip, I am getting following error.
Could you please suggest possible error here in installation.
Command used was just to check the installation 
$ NanoFilt -h

Traceback (most recent call last):
  File "/usr/local/bin/NanoFilt", line 9, in <module>
    load_entry_point('NanoFilt==1.2.0', 'console_scripts', 'NanoFilt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/nanofilt/NanoFilt.py", line 11, in <module>
    from nanomath import aveQual
  File "/usr/local/lib/python2.7/dist-packages/nanomath/__init__.py", line 1, in <module>
    from .nanomath import *
  File "/usr/local/lib/python2.7/dist-packages/nanomath/nanomath.py", line 88
    print("Number of reads:\t{}\n".format(stat["NumberOfReads"]), file=output, end="")

**Comment by wdecoster** [comment]
Hi ksanjeetsinha,

Thanks for reporting this.

Was the installation using pip successful? What is your operating system?

Is that the full error message? Please copy paste everything you get returned. 

My scripts are written (and tested) on Python3.4 and more recent versions. It's possible that they're compatible with Python2.7, but I don't guarantee it.

**Comment by wdecoster** [comment]
I just replicated your issue on Python2.7. It turns out that a submodule of NanoFilt is not compatible with Python 2.7. I have edited the README to make this clear.

If you can't upgrade to Python3 for some reason you could use a virtual environment.

**Comment by wdecoster** [comment]
I think I fixed the issue, and upgrading to NanoFilt 1.2.1 should make the script again Python2.7 compatible. Nevertheless, it wouldn't hurt to use the most up to date Python installation, but that's up to you.

**Comment by ksanjeetsinha** [comment]
Hi wdecoster,

Thank you very much for your prompt support.
I will try installing the updated one.
It was the complete error message which I was getting after return.

**Comment by wdecoster** [comment]
Glad to help, please let me know if you encounter further issues or have suggestions/feature requests.

When I replicated the error message there was one more line, starting with `SynthaxError ...` and highlighting what exactly went wrong. That's a quite important clue.

Cheers,
Wouter

**Comment by ksanjeetsinha** [comment]
Thank you very much for the prompt help.
The updated version has worked perfectly fine.
regards,
Sanjeet

**Comment by wdecoster** [comment]
Good to hear! Thanks for the feedback.
