### ISSUE TITLE
Order of the command options

### ISSUE THREAD

**Issue by Yutang-ETH** [wdecoster/nanofilt#51]
Hello @wdecoster,

I hope you are doing well. 

I would like to use nanofilt to select long reads based on their length and I would also like to trim them at both ends as I saw from nanoQC the first 30 bases and the last 20 bases are having low quality and incorrect frequency.

My question is does the order of the command option in nanofilt matter? For example, If I put -l before --headcrop, does nanofilt first select reads based on length and then do trimming? 

Thank you very much,
Yutang

**Comment by wdecoster** [comment]
Hi Yutang,

The order of the options does not matter. NanoFilt will only keep reads that fulfill all criteria.

Wouter

**Comment by Yutang-ETH** [comment]
Thanks Wouter.

Best,
Yutang
