### ISSUE TITLE
 file latency issue with nanofilt

### ISSUE THREAD

**Issue by Fatihlrcfs** [wdecoster/nanofilt#53]
Hi Dear, 
I am working on basecalling for ont with snakefile and after my run started successfully and some output files were generated an error message pop out and  run was terminated. I don't figure out the problem and ı am copied both rules for nanofilt and error message. thanks. 

the rule for nanofilt,
"""
rule nanofilt:
	input: "outputs/{chunk}.fastq.gz"
	output: "filtered/{chunk}.fastq.gz"
	log: "logs/nanofilt.{chunk}.log"
	shell:"""
cp -v {input} $TMPDIR
zcat $TMPDIR/{wildcards.chunk}.fastq.gz | NanoFilt -q 10 -l 300 |gzip > filtered/{wildcards.chunk}.fastq.gz
	"""

error mesage,

Submitted job 2998 with external jobid 'Your job 211110 ("snakejob.nanofilt.2998.sh") has been submitted'.
Waiting at most 30 seconds for missing files.
MissingOutputException in line 48 of /cluster/lrcfs/2397405/projects/nanopore_testing/data/31and61barcodedfirst/31_and_61_barcoded/20210609_1031_MN35797_FAP54362_e28d68d4/Snakefile:
Job Missing files after 30 seconds:
filtered/FAP54362_skip__e8e82a0a_783.fastq.gz
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 2998 completed successfully, but some output files are missing. 2998
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 814, in handle_job_success
  File "/cluster/lrcfs/ftiras/ftiras_env/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 247, in handle_job_success
[Fri Jun 25 18:29:17 2021]
Finished job 407.
147 of 4884 steps (3%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /cluster/lrcfs/2397405/projects/nanopore_testing/data/31and61barcodedfirst/31_and_61_barcoded/20210609_1031_MN35797_FAP54362_e28d68d4/.snakemake/log/2021-06-24T141730.152979.snakemake.log

**Comment by wdecoster** [comment]
I am not sure if this is a snakemake problem or NanoFilt problem, but you never use `{output}`?

**Comment by Fatihlrcfs** [comment]
thanks for the response it was a file latency problem and it looks like not snakemake or nanofilt based problem
