### ISSUE TITLE
command not found ,  No module named 'nanofilt'

### ISSUE THREAD

**Issue by arz19893** [wdecoster/nanofilt#54]
HI , 
I used the nanfilt to remove low quality read, tried earlier with the same command, and work fine

but today I got the message commands not found then zero output file. 

tried to delete a folder in miniconda and reinstalled it again 

1149.fastq | NanoFilt -q 12 > 1149_q12.fastq

Traceback (most recent call last):
  File "/home/arz19893/miniconda3/bin/NanoFilt", line 6, in <module>
    from nanofilt.NanoFilt import main
ModuleNotFoundError: No module named 'nanofilt'
1149.fastq: command not found

-------
the version I used V2.3 using conda 
I am new to bioinformatics and  I am not sure what I did wrong 

Thank you for your help

**Comment by wdecoster** [comment]
Since you closed this I will assume you could solve the problem?
