### ISSUE TITLE
retaining input directory structure

### ISSUE THREAD

**Issue by mawa86** [wdecoster/nanofilt#55]
Hi
Possibly a stupid question as I'm pretty new to all this, but please bear with me.
I have demultiplexed reads subdivided into barcode-specific files (eg. /reads/BC01.fastq.gz, /reads/BC02.fastq.gz , etc...). From these I have already trimmed adapters and barcodes with PoreChop. When I run nanofilt i cannot retain the barcode-wise structure, and rather get one output file with all the fastq together.

These are my lines:
`gunzip -c path/to/my/reads/*.fastq.gz | NanoFilt -l 1200 --maxlength 1800 | gzip > path/to/*_trimmed-reads.fastq.gz
`
But I only get one gzipped file named ***_trimmed-reads.fastq.gz**

Any suggestion on how to avoid manually running each barcode-specific file one after the other? i see that some program allow the -r option to reiterate within a folder, but I have not seen this in the nanofilt usage sheet..

Any help would be much appreciated

**Comment by wdecoster** [comment]
Hi,

With that command, you indeed instruct NanoFilt to create a single file.
You will have to use a bash `for` loop or use something like gnu-parallel.

Example:
```
for file in path/to/my/reads/*.fastq.gz 
do
output=$(basename $file)
gunzip -c $file | NanoFilt -l 1200 --maxlength 1800 | gzip > path/to/trimmed_${output}
done
```

Wouter

**Comment by mawa86** [comment]
> Hi,
> 
> With that command, you indeed instruct NanoFilt to create a single file.
> You will have to use a bash `for` loop or use something like gnu-parallel.
> 
> Example:
> 
> ```
> for file in path/to/my/reads/*.fastq.gz 
> do
> output=$(basename $file)
> gunzip -c $file | NanoFilt -l 1200 --maxlength 1800 | gzip > path/to/trimmed_${output}
> done
> ```
> 
> Wouter

Thanks very much Wouter! 

Martin
