### ISSUE TITLE
Is it possible to process fasta file

### ISSUE THREAD

**Issue by amit4mchiba** [wdecoster/nanofilt#57]
Hi, 

I am writing here to request if you could help me to use nanofilt for my purpose. 

I am working on a plant genome assembly, and wanted to run tgs gapcloser, which needs to use fasta file as input else it gives error. I wanted to filter my pacbio reads based on read length, and then use it as input for tgs-gapcloser. I tried using nanofilt, but seems it need fastq as input. Is there something that could be done here to meet my purpose.

Your advice will be highly appreciate.

thank you so much,

with best regards
Amit

**Comment by wdecoster** [comment]
The code would be a lot shorter. If you have NanoFilt installed you also have the requirements for this script. If you save it as "NanoFiltFa.py", do `chmod +x  NanoFiltFa.py` you can run it like you would run the normal NanoFilt.

```python
#!/usr/bin/env python

from Bio import SeqIO
import sys
from argparse import ArgumentParser

def main():
    args = get_args()
    filter_stream(args.input, args)

def get_args():
    parser = ArgumentParser(
        description="Perform length filtering of fasta data. Reads on stdin.")
    general = parser.add_argument_group(
        title='General options')
    general.add_argument("input",
                         help="input, uncompressed fastq file",
                         default=sys.stdin,
                         nargs='?')
    filtering = parser.add_argument_group(
        title='Options for filtering reads on.')
    filtering.add_argument("-l", "--length",
                           help="Filter on a minimum read length",
                           default=1,
                           type=int)
    filtering.add_argument("--maxlength",
                           help="Filter on a maximum read length",
                           default=1e12,
                           type=int)
    args = parser.parse_args()
    return args


def filter_stream(fa, args):
    for rec in SeqIO.parse(fq, "fast"):
        if args.length <= len(rec) <= args.maxlength:
            print(rec.format("fasta"), end="")


if __name__ == "__main__":
    main()
```

**Comment by amit4mchiba** [comment]
Thank you so much for your reply.
I followed ur instructions, and got following errors-
File "NanoFilt.py", line 41
    if args.length <= len(rec) <= args.maxlength \
            print(rec.format("fasta"), end="")
        ^
SyntaxError: invalid syntax

I copied the script that you mentioned in your last comment here. I am not sure as how to solve the error. I used python3 here.

Please advise me.

thank you so much,

with best regards
Amit

**Comment by amit4mchiba** [comment]
I am so sorry for another question. In the readme file, one suggested quick run command is -
gunzip -c reads.fastq.gz | NanoFilt -q 10 | gzip > highQuality-reads.fastq.gz

I wonder as to what -q stands for and what values one should use for the pacbio sequel1 generated dataset.

thank you so much in advance for your reply,

with best regards
Amit

**Comment by wdecoster** [comment]
> Thank you so much for your reply. I followed ur instructions, and got following errors- File "NanoFilt.py", line 41 if args.length <= len(rec) <= args.maxlength print(rec.format("fasta"), end="") ^ SyntaxError: invalid syntax
> 
> I copied the script that you mentioned in your last comment here. I am not sure as how to solve the error. I used python3 here.
> 
> Please advise me.
> 
> thank you so much,
> 
> with best regards Amit

I had a typo and fixed that now.


> I am so sorry for another question. In the readme file, one suggested quick run command is -
> gunzip -c reads.fastq.gz | NanoFilt -q 10 | gzip > highQuality-reads.fastq.gz
> 
> I wonder as to what -q stands for and what values one should use for the pacbio sequel1 generated dataset.
> 
> thank you so much in advance for your reply,
> 
> with best regards
> Amit

-q is for quality, which your fasta doesn't have.
You only have `--length` for the minimal length and `--maxlength` for the maximal length of your fragments of interest.

**Comment by amit4mchiba** [comment]
Thank you so much for your reply and I am so sorry to keep asking so many questions. I used the edited version of python script and this is the error I got-
Traceback (most recent call last):
  File "NanoFilt.py", line 45, in <module>
    main()
  File "NanoFilt.py", line 8, in main
    args = utils.get_args()
NameError: name 'utils' is not defined

I installed nanofilt using conda, and not using github. Does this has to do with the error. I was able to run nanofilt on test data, so, I am not sure who to make it work.

Thank you so much,

with best regards
Amit

**Comment by wdecoster** [comment]
My apologies, that is another mistake on my side. I have changed the code above. I guess that is what happens if you quickly write some code without proper testing.

**Comment by amit4mchiba** [comment]
Thank you so much. There were still very minor error but I was able to solve it. The error was due to the last few lines, and the script that I am running is-
#!/usr/bin/env python

from Bio import SeqIO
import sys
from argparse import ArgumentParser

def main():
    args = get_args()
    filter_stream(args.input, args)

def get_args():
    parser = ArgumentParser(
        description="Perform length filtering of fasta data. Reads on stdin.")
    general = parser.add_argument_group(
        title='General options')
    general.add_argument("input",
                         help="input, uncompressed fastq file",
                         default=sys.stdin,
                         nargs='?')
    filtering = parser.add_argument_group(
        title='Options for filtering reads on.')
    filtering.add_argument("-l", "--length",
                           help="Filter on a minimum read length",
                           default=1,
                           type=int)
    filtering.add_argument("--maxlength",
                           help="Filter on a maximum read length",
                           default=1e12,
                           type=int)
    args = parser.parse_args()
    return args


def filter_stream(fa, args):
    for rec in SeqIO.parse(fa, "fasta"):
        if args.length <= len(rec) <= args.maxlength:
            print(rec.format("fasta"), end="")


if __name__ == "__main__":
    main()

Thanks again.
