### ISSUE TITLE
Incomplete deflate data

### ISSUE THREAD

**Issue by xujiaweiouc** [wdecoster/nanofilt#59]
Hi, 
 When I finished " gunzip -c All_ONT.fastq.gz | NanoFilt -l 3000 | gzip > Clean.NanoFilt.fastq.gz", I want to see how many reads it has. So I ran ""pigz -dc Clean.NanoFilt.fastq.gz | awk 'NR%4==2{c++} END{print c}', but there are some errors for me. "pigz: skipping: Ath_clean.NanoFilt.fastq.gz: corrupted -- incomplete deflate data
pigz: abort: internal threads error"
 So,what is the matter?
Have a great day further and all the best.
Kind Regards,
Jiawei Xu

**Comment by wdecoster** [comment]
The file in your error message (`Ath_clean.NanoFilt.fastq.gz`) doesn't match the one in the command you mention (`Clean.NanoFilt.fastq.gz`). Are you sure you are using pigz on the right file?
Based on the error it seems the .gz file was corrupted, possibly your NanoFilt command was interrupted?
