### ISSUE TITLE
No logfile

### ISSUE THREAD

**Issue by pkerbs** [wdecoster/nanofilt#61]
Hi,
thank you for your work on this tool.
I just wanted to mention that there is no logfile output despite the use of the --logfile parameter
My command is:
```bash
gunzip -c ${sample_reads} | NanoFilt \
    --headcrop 50 \
    --tailcrop 50 \
    --quality 10 \
    --length 400 \
    --maxlength 700 \
    --logfile ${nanofilt_folder}/${sample_id}.trim.log \
    | gzip > ${nanofilt_folder}/${sample_id}_trimmed.fastq.gz
```
Best,
Paul

**Comment by jonathan-bravo** [comment]
Hey there,

As a I looked into this (not a contributor on the project), and it looks like this has to do with `root handlers`. A simple fix is to change the code [here](https://github.com/wdecoster/nanofilt/blob/cdf478c3e7e49fe658340d3fdd0211abd7a95d52/nanofilt/utils.py#L114-L121). You can add two options that might help.

```
logging.basicConfig(
    format='%asctime)s %(message)s',
    filename=logfile,
    level = logging.INFO,
    filemode = 'w',
    force = True)
```
The `filemode = 'w'` should re-write the logfile if you rerun the script and git it the same logfile name (so you don't have to worry about a running file, and the `force = True` removes the root handlers. I tested this on my local machine and was able to produce a test log file.

If that doesn't work let me know! (I know it has been a couple of months...)

**Comment by wdecoster** [comment]
I am going to close this, as NanoFilt has been superseded by [chopper](https://github.com/wdecoster/chopper), and I don't plan to make changes to the NanoFilt code.
