### ISSUE TITLE
Error using conda install

### ISSUE THREAD

**Issue by t-rex318** [wdecoster/nanofilt#62]
Hi there, while trying to install nanofilt using 'conda install -c bioconda nanofilt', I received the following stdout:

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: | 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                          
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
> 
>   - feature:/linux-64::__glibc==2.35=0
>   - python=3.9 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
> 
> Your installed version is: 2.35
> 

This is an Ubuntu 22.04 virtual machine on Windows VirtualBox. Correct me if I'm wrong but is this saying glibc is being called and is required to be above version 2.17? Since I have 2.35 do I need to use an older version?

Thanks for your help,
Trever

**Comment by wdecoster** [comment]
Could you try creating a separate environment for this?
```
conda create -n nanofilt_env nanofilt
conda activate nanofilt_env
```

**Comment by t-rex318** [comment]
Running the first line returns the PackagesNotFoundError, but creating and activating a new environment with no package, then running 'conda install -c bioconda nanofilt' installed successfully.
