### ISSUE TITLE
Tagged release for 2.8.0

### ISSUE THREAD

**Issue by skchronicles** [wdecoster/nanofilt#63]
Hello there,

Thank you for creating and maintaining this awesome tool!

Whenever you have some free time, can you please create a tagged release for the latest stable version of nanofilt?

Best Regards,
@skchronicles

**Comment by wdecoster** [comment]
I will, but I also want to point you toward https://github.com/wdecoster/chopper, which has mostly the same functionality and is much faster.

**Comment by skchronicles** [comment]
Thanks @wdecoster, I wasn't aware of this tool. I will check it out!
