### ISSUE TITLE
How to get reads with lower than 10 read quality from fastq files by using nanofilt?

### ISSUE THREAD

**Issue by kaanokay** [wdecoster/nanofilt#64]
Hi,

I want to get reads having lower than 10 read quality and higher than 10 read quality as two different fastq files. Is this possible to do that by using nanofilt?

Bw.

**Comment by wdecoster** [comment]
NanoFilt cannot, but I added a `--maxqual` option to [chopper](https://github.com/wdecoster/chopper), a faster replacement for NanoFilt. I won't change NanoFilt anymore, but feel free to open an issue in the chopper repository. With the -q option (for minimum quality) and --maxqual option (for maximum quality) you will have to run chopper twice to get the output you want, but that is still going to be faster than NanoFilt :-)

**Comment by kaanokay** [comment]
Thank you. It works for me.

Bw.

**Comment by kaanokay** [comment]
I installed chopper with conda but there is no argument called `--maxqual`. I come across issue with binary format so I need to install it via conda. Could you help me with this?

Thanks!

**Comment by wdecoster** [comment]
It is not yet updated in bioconda, but I expect it to be there today (https://github.com/bioconda/bioconda-recipes/pull/39771)

**Comment by kaanokay** [comment]
@wdecoster,

Thank so much for quick reply.

Bw.

**Comment by kaanokay** [comment]
@wdecoster hi again,

When I installed chopper via conda, it still install version 2 instead of version 3. Is that possible to update conda for version 3?

Bw.

**Comment by wdecoster** [comment]
v0.3.0 is on [conda](https://anaconda.org/bioconda/chopper)

You could try upgrading (`conda upgrade chopper`) or explicitly specify the version (`conda install chopper==v0.3.0`).

**Comment by kaanokay** [comment]
It is still still installing v2 instead of v3.
