### ISSUE TITLE
Quality score

### ISSUE THREAD

**Issue by eesiribloom** [wdecoster/nanofilt#65]
How exactly is average read quality score determined? Is it a mean Q-score per base in each read?

**Comment by wdecoster** [comment]
The per base phred/Q-scores are converted to error probabilities, then the average is taken for all probabilities of that read, after which it is converted back to the Phred scale.

**Comment by dzc0104** [comment]
“How do you recommend selecting quality and length thresholds based on read quality distribution and downstream analysis goals?

**Comment by wdecoster** [comment]
This is a 2-year old issue that is not related to what you are asking. Please open a separate issue and make your question as specific as possible.
