### ISSUE TITLE
Cant seem to get nanofilt to work on command line?

### ISSUE THREAD

**Issue by DrModupeO** [wdecoster/nanofilt#66]
Hi, i am currently trying to trim a fastq file i got from publicly available datasets with Nanofilt.
I have the following codes:

[nanofilt_script.txt](https://github.com/user-attachments/files/16029471/nanofilt_script.txt)

But i keep getting the error that says it cant find the module nanofilt and it is already installed.
Any help you can render?

**Comment by wdecoster** [comment]
NanoFilt is superseded by [chopper](https://github.com/wdecoster/chopper), or is there a reason you would need NanoFilt?

**Comment by DrModupeO** [comment]
I am working on a project and i am practicing with publicly available Nanopore dataset to create a pipeline for the sequences i am going to obtain with MinION. 
i decided to work with Nnaofilt as a filtering and trimming software.
I am new to this , so bear with me. What do you mean by chopper?

**Comment by wdecoster** [comment]
Chopper is a tool that replaces NanoFilt. I posted the link in my previous answer.
