### ISSUE TITLE
multithread max ram options

### ISSUE THREAD

**Issue by ttn1883** [wdecoster/nanofilt#67]
We are using Nanofilt for trimming reads for long read sequencing with 2 to 9 million reads. We should have a multithreading option and be able to specific how much memory when running the job.

**Comment by wdecoster** [comment]
NanoFilt is superseded by [chopper](https://github.com/wdecoster/chopper), could you have a look if that works for you?

**Comment by ttn1883** [comment]
Thank you. I didn't realized it had been replaced. chopper does not have the multithread option but I will test to see if it does it natively.
